### ISSUE TITLE
Add IEEE SA XML to Metanorma AsciiDoc conversion functionality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#183]
The conversion (except some issues) from IEEE XML to Metanorma adoc is available in mnconvert v1.20.0 (https://github.com/metanorma/mnconvert/releases/tag/v1.20.0).

How to convert from IEEE XML to Metanorma adoc:
```
java -jar mnconvert-1.20.0.jar master-1-standard.xml --output master-1-standard.adoc --imagesdir ./
```

Latest documentation with mapping between IEEE XML and Metanorma adoc and XML: [IEEE_vs_NISO_and_MN_comparison_v.0.4.docx](https://github.com/metanorma/mnconvert/files/9331516/IEEE_vs_NISO_and_MN_comparison_v.0.4.docx)

The mnconvert-ruby gem may already support this but we need to add documentation.

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mnconvert/issues/161#issuecomment-1214162506_

**Comment by CAMOBAP** [comment]
As far as I see no updates for `mnconvert-ruby` need here because this conversion doesn't require to add/pass some special flags to jar. @Intelligent2013 correct me if I'm wrong

I just double-checked there is no issues on release CI, lastest version of the gem is released
 - https://rubygems.org/gems/mnconvert
 - https://github.com/metanorma/mnconvert-ruby/actions/workflows/release.yml

@ronaldtse @Intelligent2013 feel free to reopen if I missed something
