### ISSUE TITLE
STS-Metanorma conversion: all font ligatures needs to be resolved

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#348]
The BSI PAS 2035 metadata generated this:
```adoc
:title-main-en: Retroﬁtting dwellings for improved energy efﬁciency — Speciﬁcation and guidance
```

Notice `ﬁ` is a ligature character, we need to resolve it during conversion.

**Comment by Intelligent2013** [comment]
The fonts 'BSI Gesta' and 'Frutiger' contains two ligatures:
- ﬁ FB01
- ﬂ FB02

but I'll add the conversion for these also:

- ﬀ U+FB00
- ﬃ U+FB03
- ﬄ U+FB04
- ﬅ U+FB05
- ﬆ U+FB06
(https://www.compart.com/en/unicode/block/U+FB00)

**Comment by Intelligent2013** [comment]
For information, only two document contain ligatures:
- PAS 2035
- PAS 7340
and in the titles only.

**Comment by Intelligent2013** [comment]
Done in mnconvert v1.42.0 (https://github.com/metanorma/mnconvert/releases/tag/v1.42.0)

**Comment by ronaldtse** [comment]
Thank you! Can I confirm that the STS files contained ligatures?

**Comment by Intelligent2013** [comment]
> Can I confirm that the STS files contained ligatures?

@ronaldtse only two source STS files contain ligatures (in the titles):
- reference-docs\pas\pas-2035\30400875.xml
- reference-docs\pas\pas-7340\30387840.xml

In Metanorma XML to NISO STS XML conversion mnconvert doesn't restore the ligatures, because there aren't conditions when we should restore it, and when don't. For example,
- PAS 7340 - `fi` as ligature: `<full>Framework for embedding the principles of sustainable ﬁnance in ﬁnancial services organizations — Guide</full>`,
- PAS 7341 - `fi` as two characters: `<full>Responsible and sustainable investment management&#x00A0;— Specification</full>`.

**Comment by ronaldtse** [comment]
We should not create documents with ligatures because not all fonts support them.

**Comment by ronaldtse** [comment]
Thanks for the investigation!
