### ISSUE TITLE
STS -> MN: Duplicate boilerplate in bibliography

### ISSUE THREAD

**Issue by manuel489** [metanorma/mnconvert#52]
*In relation to https://github.com/metanorma/metanorma-bsi/issues/30*

From *bs-7858*:
![issue4-generated](https://user-images.githubusercontent.com/33627611/128644590-64e0c5ea-d46b-48b2-b4f1-8e96ac051a89.PNG)

Markup:
````
For dated references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

* [[[ref_1,BS 7799-3]]], _Information security management systems – Part 3: Guidelines for information security risk management (revision of BS ISO/IEC 27005:2011)_

* [[[ref_2,BS EN ISO/IEC 27001]]], _Information technology – Security techniques – Information security management systems – Requirements_

* [[[ref_3,BS EN ISO/IEC 27002]]], _Information technology – Security techniques – Code of practice for information security controls_
````

I think the first paragraph should not be included in the markup.

**Comment by Intelligent2013** [comment]
Source STS xml has the text `For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.` in the paragraph before references:
```xml
<ref-list content-type="bibl" id="sec_bibl">
	<title>Bibliography</title>
	<ref-list>
		<title>
			<bold>Standards publications</bold>
		</title>
		<p>For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>
		<ref content-type="standard" id="ref_1">
```

Adoc:
```adoc
[bibliography]
===  Standards publications 

For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.
```

So, first paragraph in the resulted XML - from metanorma boilerplate, second one - from adoc data.

If we enclose source data in `[NOTE,type=boilerplate]` (similar to Normative References boilerplate https://www.metanorma.org/author/topics/document-format/bibliography/#predefined-text)
```
[bibliography]
===  Standards publications 

[NOTE,type=boilerplate]
--
For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.

--
```
then in resulted xml we have both paragraphs also, but second one in the note:
```xml
<clause id="_bibliography" obligation="informative" displayorder="17">
	<title depth="1">Bibliography</title>
	<references id="_standards_publications" normative="false" obligation="informative">
		<title depth="2">Standards publications</title>
		<p id="_">For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>
		<note id="_..." type="boilerplate">
			<name>NOTE</name>
			<p id="_...">For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.</p>
		</note>
		<bibitem id="ref_2" type="standard">...
```

In the available STS XML instances, the sentences `For dated references, only the edition cited applies. For undated references, the latest edition of the referenced document (including any amendments) applies.` is using in 12 xmls.
One xml (PAS 7000) contains the sentences `For dated references, only the edition cited applies. For undated references, the most recent edition of the referenced document (including any amendments) applies.` (`the most recent` instead of `the latest`).
Another xmls don't contain the sentences (and there aren't in PDF also).

To do: ignore `ref-list[@content-type="bibl"]//p` with the text starts with `For dated references, only the edition cited applies`.

**Comment by manuel489** [comment]
Fix confirmed, thanks @Intelligent2013!
Closing.
